name: Publish Maven package to GitHub Packages on release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for git-version plugin to see tags

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Publish Maven artifact to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the publication name `maven` and repository name `GitHubPackages` from build.gradle
          ./gradlew --no-daemon publishMavenPublicationToGitHubPackagesRepository \
            -PgithubPackagesUser=${{ github.actor }} \
            -PgithubPackagesToken=${{ secrets.GITHUB_TOKEN }} \
            --warning-mode all
